// Map-hint baseline (3iq, D95): each biome's TYPICAL T1 map, as the median of every
// hint metric over a fixed seed sample. Relative hints compare a map against this, so
// a hint says something the biome name doesn't. Written to src/data/hint-baseline.ts by
// `bun run sim:tables`; test/hints.test.ts fails if the committed file is stale.
import { generateGrid } from "../engine/grid";
import { mapMetrics } from "../engine/hints";
import { BIOME_IDS, HINT_METRICS } from "../data/constants";
import type { HintBaseline } from "../data/constants";

export const HINT_BASELINE_SEEDS = 40;

export function computeHintBaseline(): HintBaseline {
  const out: HintBaseline = {};
  for (const biome of BIOME_IDS) {
    const samples = Array.from({ length: HINT_BASELINE_SEEDS }, (_, i) => mapMetrics(generateGrid(`hint-base-${i}`, biome, 1)));
    const row: Record<string, number> = {};
    for (const m of HINT_METRICS) {
      const v = samples.map((s) => s[m]).sort((a, b) => a - b);
      row[m] = Math.round(((v[(v.length - 1) >> 1]! + v[v.length >> 1]!) / 2) * 1000) / 1000;
    }
    out[biome] = row;
  }
  return out;
}

export function renderHintBaseline(b: HintBaseline): string {
  return `// GENERATED by \`bun run sim:tables\` (src/sim/hint-baseline.ts) — do not edit by hand.
// Each biome's typical T1 map (median over ${HINT_BASELINE_SEEDS} seeds) per hint metric (3iq, D95).
import type { HintBaseline } from "./hints";
export const HINT_BASELINE: HintBaseline = ${JSON.stringify(b, null, 2)};
`;
}
