// Map hints (3iq / si7.6.11, D95) — qualitative whispers about a held map, rolled
// when the map is MINTED (one per family, frozen on the MapItem like its biome, D93)
// and read in town by STUDYING the map (one hint per study, for STUDY_COST).
//
// A hint must say something the biome name doesn't: every tundra is icy, so "iced
// over" on a tundra map is noise. Relative traits therefore compare the map against
// its OWN biome's typical T1 map (HINT_BASELINE, generated by `bun run sim:tables`),
// firing only when the map is remarkably high (≥ HINT_REMARKABLE × baseline) or
// scarce (≤ HINT_SCARCE × baseline). Absolute traits (a T3+ terror) fire on the raw
// value. Per family the strongest trait wins; nothing remarkable = the fallback.
// Labels stay QUALITATIVE — a number must never leak (perception guard, test-enforced).
import type { ItemStackSpec } from "./spec";
import type { BiomeId } from "./constants"; // type-only (erased, no runtime cycle)
export { HINT_BASELINE } from "./hint-baseline";

export type HintFamily = "ground" | "threat" | "bounty";
export const HINT_FAMILIES: HintFamily[] = ["ground", "threat", "bounty"];

// What a hint can measure on a generated grid. Terrain metrics are shares of ALL
// tiles; node metrics shares of all POIs; dmg/armour metrics shares of MONSTER POIs.
export type HintMetric =
  | "mountain" | "mud" | "river" | "ice" | "water" // ground (water = lake + sea + shallows)
  | "monster" | "melee" | "ranged" | "magic" | "plate" | "maxTier" // threat
  | "mining" | "wood" | "herb" | "animal" | "food"; // bounty (food = herb + animal)
export const HINT_METRICS: HintMetric[] = [
  "mountain", "mud", "river", "ice", "water",
  "monster", "melee", "ranged", "magic", "plate", "maxTier",
  "mining", "wood", "herb", "animal", "food",
];

export type HintTrait = {
  id: string;
  family: HintFamily;
  label: string;
  metric: HintMetric;
  // relative: "high"/"low" vs the biome baseline; absolute: fires at value ≥ atLeast.
  test: { dir: "high" | "low"; minAbs?: number; minBase?: number; ratio?: number } | { atLeast: number }; // ratio overrides HINT_REMARKABLE/HINT_SCARCE for this trait
};

export const HINT_REMARKABLE = 1.3; // a relative "high" trait fires at ≥ 1.3× its biome's typical share
export const HINT_SCARCE = 0.6; // a relative "low" trait fires at ≤ 0.6× its biome's typical share
export const HINT_BASELINE_FLOOR = 0.02; // baselines below this read as this (a near-absent terrain can't make every trace "remarkable")

// Ordered: on an exact score tie the earlier trait wins. `minAbs` = the raw share must
// also reach this (so "cut by rivers" needs real rivers, not 2 tiles); `minBase` = a
// "low" trait only speaks where the biome normally HAS the thing (no "little water"
// on a desert map).
export const MAP_HINTS: HintTrait[] = [
  // ground — which movement gear earns its slot (climbing-pick, waders, raft/longboat, cleats)
  { id: "ridges", family: "ground", label: "walled by ridges", metric: "mountain", test: { dir: "high", minAbs: 0.15 } },
  { id: "open-country", family: "ground", label: "open country", metric: "mountain", test: { dir: "low", minBase: 0.05 } },
  { id: "boggy", family: "ground", label: "boggy ground", metric: "mud", test: { dir: "high", minAbs: 0.15 } },
  { id: "rivers", family: "ground", label: "cut by rivers", metric: "river", test: { dir: "high", minAbs: 0.03 } },
  { id: "wet", family: "ground", label: "much open water", metric: "water", test: { dir: "high", minAbs: 0.1 } },
  { id: "dry", family: "ground", label: "little water", metric: "water", test: { dir: "low", minBase: 0.05 } },
  { id: "iced", family: "ground", label: "iced over", metric: "ice", test: { dir: "high", minAbs: 0.1 } },
  // threat — what to wear and wield
  { id: "ancients", family: "threat", label: "something old lairs here", metric: "maxTier", test: { atLeast: 3 } },
  { id: "swarming", family: "threat", label: "crawling with monsters", metric: "monster", test: { dir: "high" } },
  { id: "quiet", family: "threat", label: "quiet country", metric: "monster", test: { dir: "low" } },
  { id: "steel", family: "threat", label: "they come at you with claws and steel", metric: "melee", test: { dir: "high", minAbs: 0.5 } },
  { id: "archers", family: "threat", label: "archers about", metric: "ranged", test: { dir: "high", minAbs: 0.3 } },
  { id: "spells", family: "threat", label: "the locals strike with magic", metric: "magic", test: { dir: "high", minAbs: 0.3 } },
  { id: "shells", family: "threat", label: "hard-shelled beasts", metric: "plate", test: { dir: "high", minAbs: 0.3 } },
  // bounty — which gather tools (and how much food) to bring
  { id: "ore", family: "bounty", label: "ore-rich", metric: "mining", test: { dir: "high", minAbs: 0.12, ratio: 1.2 } }, // node mixes vary less than terrain: bounty fires at 1.2×
  { id: "timber", family: "bounty", label: "well-timbered", metric: "wood", test: { dir: "high", minAbs: 0.15, ratio: 1.2 } },
  { id: "game", family: "bounty", label: "game-rich", metric: "animal", test: { dir: "high", minAbs: 0.2, ratio: 1.2 } },
  { id: "forage", family: "bounty", label: "lush forage", metric: "herb", test: { dir: "high", minAbs: 0.2, ratio: 1.2 } },
  { id: "thin", family: "bounty", label: "thin forage", metric: "food", test: { dir: "low", ratio: 0.8 } }, // the food warning: pack more rations
];
// Nothing remarkable in a family → its fallback (still a hint: "nothing unusual" is information).
export const HINT_FALLBACK: Record<HintFamily, { id: string; label: string }> = {
  ground: { id: "ordinary-ground", label: "ordinary country" },
  threat: { id: "usual-dangers", label: "the usual dangers" },
  bounty: { id: "mixed-bounty", label: "a bit of everything" },
};

// Studying a held map in town reveals its next hint (D95). A copper sink (copper was
// the playtest's "trap" material; ore-ink is its other sink). Flat across tiers.
export const STUDY_COST: ItemStackSpec[] = [{ defId: "copper-ore", qty: 1 }];

// The generated baseline's shape: each biome's typical (median, T1) value per metric.
export type HintBaseline = Partial<Record<BiomeId, Partial<Record<HintMetric, number>>>>;
